In [1]:
import mysql.connector


mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  #database='joins'
  
)

print(mydb)
mycursor = mydb.cursor(buffered=True)

<mysql.connector.connection_cext.CMySQLConnection object at 0x000002427926D490>

In [3]:
mycursor.execute("CREATE DATABASE emp")

In [4]:
mycursor.execute("USE emp")
mycursor.execute("CREATE TABLE employee(id INT(6),name VARCHAR(32),post VARCHAR(32),salary INT(32))")

sql = "INSERT INTO employee (id,name,post,salary) VALUES (%s,%s,%s,%s)"
val = [
    (1,'sumit','manager',70000),
    (2,'rahul','assistant manager',40000),
    (3,'neha','receptionist',30000),
    (4,'manish','electrecian',20000),
    (5,'parul','accountant',50000)
]
mycursor.executemany(sql,val)
mydb.commit()

In [5]:
mycursor.execute("USE emp")
#Checking for employee id, if it already exists or not.
def check_employee(employee_id):
    #query to select all the rows from the employee table
    sql = 'SELECT * FROM employee where id=%s'
    
    # making cursor buffered to make
    # rowcount method work properly
    c = mydb.cursor(buffered=True)
    data = (employee_id,)
    
    # Executing the SQL Query
    c.execute(sql, data)
    
    # rowcount method to find
    # number of rows with given values
    r = c.rowcount
     
    if r == 1:
        return True
    else:
        return False
    
def add_employ():
    
    Id = input("Enter employee id:")
    
    #checking if the id already exists
    if(check_employee(Id)==True):
        print("Employee already exists.\nTry again\n")
        menu()
    else:
        Name = input("Enter employee name:")
        Post = input("Enter employee post:")
        Salary = input("Enter employee salary:")
        data = (Id,Name,Post,Salary)
        
        #inserting new employee details into the table
        sql = 'INSERT INTO employee VALUES (%s,%s,%s,%s)'
        c = mydb.cursor()
        
        #executing the query
        c.execute(sql,data)
        
        #commit() the changes
        mydb.commit()
        print("Employee has been added successfully")
        menu()

def remove_employ():
    
    Id = input("Enter employee id:")
    
    #checking if input employee id exists or not
    if (check_employee(Id)==False):
        print("Employee does not exist.\nPlease verify the ID and retry\n")
        menu()
    
    else:
        sql = 'DELETE FROM employee where Id = %s'
        data = (Id,)
        c = mydb.cursor()
        
        c.execute(sql,data)
        
        #committing the changes
        mydb.commit()
        print("Employee removed")
        menu()
        
def promote_employ():
    
    Id = input("Enter employee id:")
    
    #checking if employee id exists
    if (check_employee(Id) == False):
        print("Employee does not exists.\nPlease verify the ID and retry.\n")
        menu()
    else:
        Amount =(input("Enter increase in salary:"))
#         Amount = int(input("Enter increase in salary:"))
        
        #query to fetch salary with the employee id
        sql = 'SELECT salary FROM employee WHERE id = %s'
        data = (Id,)
        c= mydb.cursor()
        
        #executing the query
        c.execute(sql,data)
        
        #Fetching the salary
        r = c.fetchone()
        t = r[0]+int(Amount)
        
        #query to SQL
        sql = 'UPDATE employee SET salary=%s where id=%s'
        d = (t,Id)
        
        #execute the query
        c.execute(sql,d)
        
        #commit changes
        mydb.commit()
        print("Employee promoted")
        menu()

def display_employees():
    #query to select all rows from employee table
    sql = 'SELECT * FROM employee'
    c = mydb.cursor()
    
    #executing the SQL query
    c.execute(sql)
    
    #Fetching all details of all the employee 
    r = c.fetchall()
    for i in r:
        print("Employee id:",i[0])
        print("Employee Name:",i[1])
        print("Employee Post:",i[2])
        print("Employee Salary:",i[3])
        print("-----------------------\
        ----------------------------------\
        ------------------------------------")
    menu()

def menu():
    print("Welcome to Employee Management Data")
    print("Press ")
    print("1 to Add employee")
    print("2 to Remove employee")
    print("3 to Promote employee")
    print("4 to Display employee details")
    print("5 to Exit")
    
    #Taking choice from user
    ch = int(input("Enter your choice:"))
    if ch == 1:
        add_employ()
    elif ch ==2:
        remove_employ()
    elif ch ==3:
        promote_employ()
    elif ch == 4:
        display_employees()
    elif ch == 5:
        exit(0)
    else:
        print("Invalid choice\nPlease make a valid choice\n")
        menu()

#calling menu fn:
menu()

Welcome to Employee Management Data
Press
1 to Add employee
2 to Remove employee
3 to Promote employee
4 to Display employee details
5 to Exit
Employee has been added successfully
Welcome to Employee Management Data
Press
1 to Add employee
2 to Remove employee
3 to Promote employee
4 to Display employee details
5 to Exit

: